<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;
    charset=utf-8"/>
    <base href="/" />
    <link rel="stylesheet" type="text/css" href="/css/master.css" />
</head>
<body>
    <div id="header">
        <div id="logo">
        <img src="/images/logo.png" />
        </div>
        <div id="menu">
            <a href="<?php echo $this->url(array(), 'home');?>">HOME</a>
        <a href="<?php echo $this->url(array('page' => 'services'), 'static-content');?>">SERVICES</a>
         <a href="<?php echo $this->url(array('page' => 'about-us'), 'static-content');?>">ABOUT US</a>
        <a href="#">CONTACT</a>
        </div>
    </div>
    
    <div id="content">
        <?php echo $this->layout()->content ?>
    </div>
    
    <div id="footer">
        <p>
            Copyright with <a href="http://www.facebook.com/ashishtam">Ashish Tamrakar</a>
        </p>
    </div>
</body>
</html>
